### ISSUE TITLE
Authorization failed, please try again

### ISSUE THREAD

**Issue by AlexMnrs** [storax/pytwitch#18]
Hello!

I'm trying to use this app but getting the next errors:

```
C:\Users\alexm\Desktop>python twitcherino.py
Press enter after you authorize with Twitch
127.0.0.1 - - [20/Nov/2016 20:16:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2016 20:16:52] "GET /success HTTP/1.1" 200 -

Traceback (most recent call last):
  File "twitcherino.py", line 65, in <module>
    main()
  File "twitcherino.py", line 46, in main
    assert ts.authorized, "Authorization failed, please try again."
AssertionError: Authorization failed, please try again.
```

I go to my Twitch account and PyTwitcher is on the list of authorized apps, so I don't know why the app is throwing me that errors.. Any suggestions? Thank you!

**Comment by storax** [comment]
I don't know if there might be any issues on Windows, I'm unaware of. Like Firewall or something similar. Do you get a white page that says "Pytwitcher authorized"? If you see that page you could try firebug or a similar addon to check if a post request is getting send back to the local python server (it sends the token it got from twitch to your running python instance). What branch are you using? This project hasn't been updated in a long time. The feature/app branch used to work ok for some time but I just tried it and I get errors and segfaults. I don't have the time to work on it. I'm really sorry. But would be happy to accept any kind of contribution, do reviews, help etc.

**Comment by AlexMnrs** [comment]
Yep! I get the white page saying "Pytwitcher authorized", but I don't know how to check the post request with firebug. Uhm... branch? I don't know... I just downloaded the py file and followed the below instructions for the setup. But if you don't have time to work on it, it's okay, no problem... Thank you anyways :(
